-- Create table 'BIKE_STATION_INFORMATION'
CREATE
OR REPLACE TABLE CITIBIKE.RAW.BIKE_STATION_INFORMATION cluster by (batch_run_date)(
  WINDOW_START TIMESTAMP_NTZ(9),
  STATION_ID VARCHAR(16777216),
  LONGITUDE FLOAT,
  LATITUDE FLOAT,
  NAME VARCHAR(16777216),
  REGION_ID VARCHAR(16777216),
  CAPACITY NUMBER(38, 0),
  LAST_UPDATED_TMP TIMESTAMP_NTZ(9),
  BATCH_RUN_DATE DATE
);

CREATE STAGE CITIBIKE.RAW.BIKE_STATION_INFORMATION_STAGE;


-- Create table 'BIKE_STATION_STATUS'
CREATE
OR REPLACE TABLE CITIBIKE.RAW.BIKE_STATION_STATUS cluster by (batch_run_date)(
  WINDOW_START TIMESTAMP_NTZ(9),
  STATION_ID VARCHAR(16777216),
  LEGACY_ID NUMBER(38, 0),
  NUM_EBIKES_AVAILABLE NUMBER(38, 0),
  NUM_BIKES_AVAILABLE NUMBER(38, 0),
  NUM_BIKES_DISABLED NUMBER(38, 0),
  IS_INSTALLED NUMBER(38, 0),
  IS_RETURNING NUMBER(38, 0),
  IS_RENTING NUMBER(38, 0),
  EIGHTD_HAS_AVAILABLE_KEYS BOOLEAN,
  NUM_DOCKS_AVAILABLE NUMBER(38, 0),
  NUM_DOCKS_DISABLED NUMBER(38, 0),
  NUM_SCOOTERS_AVAILABLE NUMBER(38, 0),
  NUM_SCOOTERS_UNAVAILABLE NUMBER(38, 0),
  MAX_LAST_REPORTED TIMESTAMP_NTZ(9),
  MAX_LAST_UPDATED TIMESTAMP_NTZ(9),
  BATCH_RUN_DATE DATE
);

CREATE STAGE CITIBIKE.RAW.BIKE_STATION_STATUS_STAGE